### ISSUE TITLE
Error code 405 when switching to Production environment

### ISSUE THREAD

**Issue by vincentngo3151991** [Shopify/mobile-buy-sdk-android#258]
Hi,

I am testing Sample App. It works fine on ENVIRONMENT_TEST but switching from WalletConstants.ENVIRONMENT_TEST to WalletConstants.ENVIRONMENT_PRODUCTION produces WalletConstants.ERROR_CODE_MERCHANT_ACCOUNT_ERROR. It seems like there is something missing when configures the shopify admin panel. Any pointers would be helpful. 

If possible, please also provide step by step instructions on how to integrate Android Pay.

Thanks

**Comment by krisorr** [comment]
Hi,

Great to see that you are interested in integrating Android Pay.
This would be a great question for https://ecommerce.shopify.com/c/shopify-apis-and-technology, and I would encourage you to post questions about the usage of the SDK to the forums going forward so that the Shopify community can share the knowledge.

The WalletConstants.ERROR_CODE_MERCHANT_ACCOUNT_ERROR is expected when using the sample application with WalletConstants.ENVIRONMENT_PRODUCTION.  For an app to work in production it requires that it is first whitelisted with Google, and is a an APK signed with a production keystore.

Please refer to the documentation here: https://developers.google.com/android-pay/ which walks through how to set an app up to accept Android Pay.

In particular, please take a look at https://developers.google.com/android-pay/get-started which details what you need to do qualify your apk and publish it on the Play Store with Android Pay.
The Google documentation is quite thorough, and if you have any questions directly related to Android Pay that are not covered there are contact links to reach out to the experts at Google.

This document: https://help.shopify.com/api/sdks/mobile-buy-sdk/android/integration-guide/checkout has information about how to complete a Checkout on Shopify with Android Pay.
