### ISSUE TITLE
Update RELEASE_NOTES.md

### ISSUE THREAD

**Issue by Yazon2006** [Shopify/mobile-buy-sdk-android#386]
There are no updates after 1.2.0 version in release notes. What changed? Is it worth to upgrade to new version? Have you decomposed retrofit, okhttp, okhttp-urlconnection, com.android.support and picasso from your "framework" (can't say that it is library because of lot of dependencies)?

**Comment by dbart01** [comment]
Up-to-date release notes can always be found in [Release on GitHub](https://github.com/Shopify/mobile-buy-sdk-android/releases).

**Comment by julieaus2010** [comment]
Hi no thanks will not upgrade when I cant advertise because of prices cganges that need to check everyday and fix it.?
I have not that I have schanges i did  i dont understand why support couldnt find my fb shop.  Whoever ot is and seen like shopify not security and xhanging pw no good. I feel someone else who can get into my account and start advistise their companies on my fb are bunch of users.
