### ISSUE TITLE
Where can I get idempotencyKey for credit card checkout?

### ISSUE THREAD

**Issue by kebbbnnn** [Shopify/mobile-buy-sdk-android#434]
Hi, the `CreditCardPaymentInput` has `idempotencyKey` param.

`
Storefront.CreditCardPaymentInput input = new Storefront.CreditCardPaymentInput(amount, idempotencyKey, billingAddress,
      creditCardVaultToken);
`

but as I've search through the sdk its value can be taken from `PaymentToken` which can be generated only with `PayHelper#extractPaymentToken` that takes android pay's `FullWallet `. Is there any way to generate this for credit card checkout? Thanks in advance.

**Comment by sav007** [comment]
From the JavaDocs you can find that IdempotencyKey is:
"A unique client generated key used to avoid duplicate charges. When a duplicate payment is found, the original is returned instead of creating a new one."

This key is generated on your side (should be unique as example you can use UUID) once per payment and provided to complete checkout. It's used to avoid payment duplication requests if you have any retry logic for the network requests.
