### ISSUE TITLE
How to Add Mobile Application to sales Channel

### ISSUE THREAD

**Issue by Bhargavasrinivas** [Shopify/mobile-buy-sdk-android#572]
Hello

I had developed  Android Application Using shopify store front apis 
but how to add this mobile application in the sales channel . 
i am new to this shopify and i have no idea that how to list our android application
 in the sales channel.

**Comment by morganmccunn** [comment]
Hi @Bhargavasrinivas you can check out the documentation in the help center [here](https://help.shopify.com/en/api/guides/sales-channel-sdk) or reach out to the App Store team if you have questions: apps@shopify.com.

**Comment by Bhargavasrinivas** [comment]
Hi @morganmccunn  my question is i developed a  Android Mobile app Using Store Front api , using the sdk   'com.shopify.mobilebuysdk:buy3:3.2.2' and now how to add this  Mobile app in shopify sales channel ,like i want to see how many orders has been made by the Mobile app like wise , i gone through the link you had given me but i didn't find any solution.

**Comment by morganmccunn** [comment]
Hi @Bhargavasrinivas - oh i see, I think I misunderstood your question. The name of your private app is automatically recorded as the sales channel when an order is placed through it. You can go to your Orders in the Shopify admin, filter by Sales channels and select the name of your private app. 
[![alt](https://screenshot.click/10-29-5noyc-s7tpq.jpg)](https://screenshot.click/10-29-5noyc-s7tpq.jpg)

If the name of your app does not show up, it's because there are no orders that have been placed through this channel yet.

Your reports in the Analytics section of Shopify will also have all order classified by the name of the sales channel (ie. name of private app.)

Hope that helps.
