### ISSUE TITLE
Fetch available Discount codes and details

### ISSUE THREAD

**Issue by venkataseshaiahudatha** [Shopify/mobile-buy-sdk-android#604]
Hi,

We are using Shopify mobile sdk version 3.3.0. Can you please help us to explore available discount codes and discount code details . We want to show all the available discounts in Android mobile applications.

Appreciated for quick help.

Thanks,
Seshu

**Comment by RubensHardt** [comment]
Hi,

My company is having the same issue. Does Shopify have any plans to update the SDK for Android to match the iOS SDK?

Thanks, 
Rubens

**Comment by rebeccajfriedman** [comment]
@RubensHardt Please see the comment here: https://github.com/Shopify/mobile-buy-sdk-android/issues/605#issuecomment-492411710

@venkataseshaiahudatha we don't currently expose a list of discount codes in our API. I have added a ticket to our backlog for this. As a workaround, you could consider using Automatic Discounts instead of discount codes.

**Comment by morganmccunn** [comment]
Hi folks - this is an interesting use case! Best practice has been to use content (eg. banners, images, or text) to inform customers of the available discount codes for their products. This is because there are often hidden, or exclusive discount codes that merchants will use (eg. VIP program, first-time buyer, promotional discounts related to event attendees). 

Exposing this through the API makes it so that users _could_ see all the discount codes, even the hidden/exclusive ones. Perhaps you don't have these use cases now, but it's possible in the future 🙃 

Beyond using content to display the current discount codes, the [automatic discount codes](https://help.shopify.com/en/manual/promoting-marketing/discount-codes/automatic-discounts) are a great workaround as it doesn't require customer action (it's applied automatically!) and you don't need to update any content on your site! 

If automatic discounts or content updates don't work for your companies, I'd love to learn more about the user experience you're trying to enable here!

**Comment by morganmccunn** [comment]
Will close this for now, but please re-open if you have thoughts or comments on the above 🙂 thanks!
